name: messages
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_lints: ^5.0.0